<?php $this->htmlElement('body')->appendAttribute('class', 'activity-log-events'); ?>

<?php echo $this->pageTitle($this->translate('Events'), 1, $this->translate('Activity Log')); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<?php if ($loggedEvents): ?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('ID'); ?></th>
            <th><?php echo $this->translate('Date'); ?></th>
            <th><?php echo $this->translate('User'); ?></th>
            <th><?php echo $this->translate('IP'); ?></th>
            <th><?php echo $this->translate('Resource'); ?></th>
            <th><?php echo $this->translate('Event'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($loggedEvents as $loggedEvent): ?>
        <?php
        $dateTime = new DateTime('@' . $loggedEvent->created());
        $dateTime->setTimezone(new DateTimeZone($this->setting('time_zone', 'UTC')));
        $user = $loggedEvent->user();
        ?>
        <tr>
            <td><?php echo $loggedEvent->id(); ?></td>
            <td><?php echo $dateTime->format('Y-m-d H:i:s.v'); ?></td>
            <td><?php echo $user ? sprintf('%s<br>%s', $user->link($user->name()), $user->displayRole()) : ''; ?></td>
            <td><?php echo $this->hyperlink($loggedEvent->ip(), sprintf('https://whatismyipaddress.com/ip/%s', $loggedEvent->ip()), ['target' => '_blank']); ?></td>
            <td><?php echo $loggedEvent->resource(); ?></td>
            <td><?php echo $loggedEvent->event(); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $this->translate('No events found.'); ?></p>
</div>

<?php endif; ?>
