<?php $this->htmlElement('body')->appendAttribute('class', 'activity-log-events'); ?>

<?php echo $this->pageTitle($this->translate('Events'), 1, $this->translate('Activity Log')); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div class="filter-controls">
    <?php echo $this->form()->openTag($eventFilterForm); ?>
    <?php echo $this->formElement($eventFilterForm->get('id')); ?>
    <?php echo $this->formElement($eventFilterForm->get('user')); ?>
    <?php echo $this->formElement($eventFilterForm->get('user_role')); ?>
    <?php echo $this->formElement($eventFilterForm->get('ip')); ?>
    <?php echo $this->formElement($eventFilterForm->get('event')); ?>
    <?php echo $this->formElement($eventFilterForm->get('resource')); ?>
    <?php echo $this->formElement($eventFilterForm->get('resource_id')); ?>
    <?php echo $this->formElement($eventFilterForm->get('from')); ?>
    <?php echo $this->formElement($eventFilterForm->get('to')); ?>
    <button type="submit"><?php echo $this->translate('Apply filters'); ?></button>
    <a class="button" href="<?php echo $this->escapeHtml($this->url(null, [], true)); ?>"><?php echo $this->translate('Clear filters'); ?></a>
    <?php echo $this->form()->closeTag(); ?>
</div>

<?php if ($loggedEvents): ?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $this->translate('ID'); ?></th>
            <th><?php echo $this->translate('Date'); ?></th>
            <th><?php echo $this->translate('User'); ?></th>
            <th><?php echo $this->translate('IP'); ?></th>
            <th><?php echo $this->translate('Event'); ?></th>
            <th><?php echo $this->translate('Resource'); ?></th>
            <th><?php echo $this->translate('Message'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($loggedEvents as $loggedEvent): ?>
        <?php
        $dateTime = new DateTime('@' . $loggedEvent->created());
        $dateTime->setTimezone(new DateTimeZone($this->setting('time_zone', 'UTC')));
        $user = $loggedEvent->user();
        $eventParams = $this->trigger(
            'activity_log.event_messages',
            ['loggedEvent' => $loggedEvent, 'messages' => []],
            true,
            [$loggedEvent->event()]
        );
        ?>
        <tr>
            <td><?php echo $loggedEvent->id(); ?></td>
            <td><?php echo $dateTime->format('Y-m-d<\b\r>H:i:s.v'); ?></td>
            <td><?php echo $user ? sprintf('%s<br>%s', $user->link($user->name()), $user->role()) : ''; ?></td>
            <td><?php echo $this->hyperlink($loggedEvent->ip(), sprintf('https://whatismyipaddress.com/ip/%s', $loggedEvent->ip()), ['target' => '_blank']); ?></td>
            <td><?php echo $loggedEvent->event(); ?></td>
            <td><?php echo $loggedEvent->resource(); ?></td>
            <td>
                <?php echo implode('<br>', $eventParams['messages']); ?>
                <div><?php echo $this->hyperlink($this->translate('View event data'), '#', [
                    'data-sidebar-selector' => '#show-details',
                    'data-sidebar-content-url' => $this->url('admin/activity-log/id', ['action' => 'show-details', 'id' => $loggedEvent->id()], true),
                    'class' => 'sidebar-content',
                ]); ?></div>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div id="show-details" class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $this->translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $this->translate('No events found.'); ?></p>
</div>

<?php endif; ?>
